from .base_exception import BaseException

class ValidationError(BaseException):
    pass 